import { Language } from "./types";

export const languages: {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
];

export const languageNames: Record<Language, string> = {
  en: "English",
  fr: "French",
  de: "German",
  it: "Italian",
  es: "Spanish",
  pt: "Portuguese",
};

export const ui: Record<
  Language,
  {
    appTitle: string;
    selectLanguage: string;
    selectLevel: string;
    generate: string;
    generating: string;
    kanjiOfTheDay: string;
    grammarOfTheDay: string;
    writing: string;
    onyomi: string;
    kunyomi: string;
    meaning: string;
    vocabulary: string;
    structure: string;
    examples: string;
    fillInBlank: string;
    jpToLang: string;
    langToJp: string;
    kanjiMeaning: string;
    revealAnswer: string;
    hideAnswer: string;
    chooseAnswer: string;
    correct: string;
    incorrect: string;
    back: string;
    error: string;
    tryAgain: string;
    exercise: string;
    correctMe: string;
    correcting: string;
    score: string;
    correctedVersion: string;
    corrections: string;
    writeTranslation: string;
    yourTranslation: string;
    profile: string;
    language: string;
    jlptLevel: string;
    save: string;
    kanjiList: string;
    kanji: string;
    strokes: string;
    loading: string;
    studySession: string;
    kanjiDictionary: string;
    searchKanji: string;
    noResults: string;
    loadVocabulary: string;
    apiKey: string;
    apiKeyPlaceholder: string;
    apiKeyRequired: string;
    levelComplete: string;
    startOver: string;
    nextLevel: string;
    kanjiProgress: string;
    grammarProgress: string;
    reading: string;
    generateReading: string;
    generatingReading: string;
    showFurigana: string;
    hideFurigana: string;
    showTranslation: string;
    hideTranslation: string;
    keyVocabulary: string;
    comprehension: string;
  }
> = {
  en: {
    appTitle: "Kurodo",
    selectLanguage: "Select your language",
    selectLevel: "Select your JLPT level",
    generate: "Generate Study Session",
    generating: "Generating...",
    kanjiOfTheDay: "Kanji of the Day",
    grammarOfTheDay: "Grammar of the Day",
    writing: "Writing",
    onyomi: "On'yomi",
    kunyomi: "Kun'yomi",
    meaning: "Meaning",
    vocabulary: "Vocabulary",
    structure: "Structure",
    examples: "Examples",
    fillInBlank: "Fill in the Blank",
    jpToLang: "Japanese → English",
    langToJp: "English → Japanese",
    kanjiMeaning: "Kanji Meaning",
    revealAnswer: "Reveal Answer",
    hideAnswer: "Hide Answer",
    chooseAnswer: "Choose the correct answer",
    correct: "Correct!",
    incorrect: "Incorrect",
    back: "Back",
    error: "An error occurred. Please try again.",
    tryAgain: "Try Again",
    exercise: "Exercise",
    correctMe: "Correct Me",
    correcting: "Correcting...",
    score: "Score",
    correctedVersion: "Corrected version",
    corrections: "Corrections",
    writeTranslation: "Write your Japanese translation below",
    yourTranslation: "Your translation in Japanese...",
    profile: "Profile",
    language: "Language",
    jlptLevel: "JLPT Level",
    save: "Save",
    kanjiList: "Kanji List",
    kanji: "kanji",
    strokes: "Strokes",
    loading: "Loading...",
    studySession: "Study Session",
    kanjiDictionary: "Kanji Dictionary",
    searchKanji: "Search by kanji, reading, or meaning...",
    noResults: "No kanji found",
    loadVocabulary: "Load Vocabulary Examples",
    apiKey: "Anthropic API Key",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyRequired: "Please set your Anthropic API key in the profile settings.",
    levelComplete: "You've covered all kanji and grammar for this level!",
    startOver: "Start Over",
    nextLevel: "Next Level",
    kanjiProgress: "Kanji",
    grammarProgress: "Grammar",
    reading: "Reading",
    generateReading: "Generate Reading Passage",
    generatingReading: "Generating...",
    showFurigana: "Show Furigana",
    hideFurigana: "Hide Furigana",
    showTranslation: "Show Translation",
    hideTranslation: "Hide Translation",
    keyVocabulary: "Key Vocabulary",
    comprehension: "Comprehension",
  },
  fr: {
    appTitle: "Kurodo",
    selectLanguage: "Choisissez votre langue",
    selectLevel: "Choisissez votre niveau JLPT",
    generate: "Générer une session d'étude",
    generating: "Génération en cours...",
    kanjiOfTheDay: "Kanji du jour",
    grammarOfTheDay: "Grammaire du jour",
    writing: "Écriture",
    onyomi: "On'yomi",
    kunyomi: "Kun'yomi",
    meaning: "Signification",
    vocabulary: "Vocabulaire",
    structure: "Structure",
    examples: "Exemples",
    fillInBlank: "Compléter la phrase",
    jpToLang: "Japonais → Français",
    langToJp: "Français → Japonais",
    kanjiMeaning: "Sens du Kanji",
    revealAnswer: "Révéler la réponse",
    hideAnswer: "Masquer la réponse",
    chooseAnswer: "Choisissez la bonne réponse",
    correct: "Correct !",
    incorrect: "Incorrect",
    back: "Retour",
    error: "Une erreur est survenue. Veuillez réessayer.",
    tryAgain: "Réessayer",
    exercise: "Exercice",
    correctMe: "Corriger",
    correcting: "Correction en cours...",
    score: "Score",
    correctedVersion: "Version corrigée",
    corrections: "Corrections",
    writeTranslation: "Écrivez votre traduction en japonais ci-dessous",
    yourTranslation: "Votre traduction en japonais...",
    profile: "Profil",
    language: "Langue",
    jlptLevel: "Niveau JLPT",
    save: "Enregistrer",
    kanjiList: "Liste des Kanji",
    kanji: "kanji",
    strokes: "Traits",
    loading: "Chargement...",
    studySession: "Session d'étude",
    kanjiDictionary: "Dictionnaire de Kanji",
    searchKanji: "Chercher par kanji, lecture ou sens...",
    noResults: "Aucun kanji trouvé",
    loadVocabulary: "Charger des exemples de vocabulaire",
    apiKey: "Clé API Anthropic",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyRequired: "Veuillez configurer votre clé API Anthropic dans les paramètres du profil.",
    levelComplete: "Vous avez couvert tous les kanji et la grammaire de ce niveau !",
    startOver: "Recommencer",
    nextLevel: "Niveau suivant",
    kanjiProgress: "Kanji",
    grammarProgress: "Grammaire",
    reading: "Lecture",
    generateReading: "Générer un texte de lecture",
    generatingReading: "Génération en cours...",
    showFurigana: "Afficher les furigana",
    hideFurigana: "Masquer les furigana",
    showTranslation: "Afficher la traduction",
    hideTranslation: "Masquer la traduction",
    keyVocabulary: "Vocabulaire clé",
    comprehension: "Compréhension",
  },
  de: {
    appTitle: "Kurodo",
    selectLanguage: "Wählen Sie Ihre Sprache",
    selectLevel: "Wählen Sie Ihr JLPT-Level",
    generate: "Lernsitzung generieren",
    generating: "Wird generiert...",
    kanjiOfTheDay: "Kanji des Tages",
    grammarOfTheDay: "Grammatik des Tages",
    writing: "Schreiben",
    onyomi: "On'yomi",
    kunyomi: "Kun'yomi",
    meaning: "Bedeutung",
    vocabulary: "Vokabular",
    structure: "Struktur",
    examples: "Beispiele",
    fillInBlank: "Lückentext",
    jpToLang: "Japanisch → Deutsch",
    langToJp: "Deutsch → Japanisch",
    kanjiMeaning: "Kanji-Bedeutung",
    revealAnswer: "Antwort anzeigen",
    hideAnswer: "Antwort verbergen",
    chooseAnswer: "Wählen Sie die richtige Antwort",
    correct: "Richtig!",
    incorrect: "Falsch",
    back: "Zurück",
    error: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    tryAgain: "Erneut versuchen",
    exercise: "Übung",
    correctMe: "Korrigieren",
    correcting: "Wird korrigiert...",
    score: "Punktzahl",
    correctedVersion: "Korrigierte Version",
    corrections: "Korrekturen",
    writeTranslation: "Schreiben Sie Ihre japanische Übersetzung unten",
    yourTranslation: "Ihre Übersetzung auf Japanisch...",
    profile: "Profil",
    language: "Sprache",
    jlptLevel: "JLPT-Stufe",
    save: "Speichern",
    kanjiList: "Kanji-Liste",
    kanji: "Kanji",
    strokes: "Striche",
    loading: "Laden...",
    studySession: "Lernsitzung",
    kanjiDictionary: "Kanji-Wörterbuch",
    searchKanji: "Suche nach Kanji, Lesung oder Bedeutung...",
    noResults: "Keine Kanji gefunden",
    loadVocabulary: "Vokabelbeispiele laden",
    apiKey: "Anthropic API-Schlüssel",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyRequired: "Bitte setzen Sie Ihren Anthropic API-Schlüssel in den Profileinstellungen.",
    levelComplete: "Sie haben alle Kanji und Grammatik für dieses Level abgedeckt!",
    startOver: "Neu starten",
    nextLevel: "Nächstes Level",
    kanjiProgress: "Kanji",
    grammarProgress: "Grammatik",
    reading: "Lesen",
    generateReading: "Lesetext generieren",
    generatingReading: "Wird generiert...",
    showFurigana: "Furigana anzeigen",
    hideFurigana: "Furigana verbergen",
    showTranslation: "Übersetzung anzeigen",
    hideTranslation: "Übersetzung verbergen",
    keyVocabulary: "Schlüsselvokabular",
    comprehension: "Verständnis",
  },
  it: {
    appTitle: "Kurodo",
    selectLanguage: "Seleziona la tua lingua",
    selectLevel: "Seleziona il tuo livello JLPT",
    generate: "Genera sessione di studio",
    generating: "Generazione in corso...",
    kanjiOfTheDay: "Kanji del giorno",
    grammarOfTheDay: "Grammatica del giorno",
    writing: "Scrittura",
    onyomi: "On'yomi",
    kunyomi: "Kun'yomi",
    meaning: "Significato",
    vocabulary: "Vocabolario",
    structure: "Struttura",
    examples: "Esempi",
    fillInBlank: "Completa la frase",
    jpToLang: "Giapponese → Italiano",
    langToJp: "Italiano → Giapponese",
    kanjiMeaning: "Significato del Kanji",
    revealAnswer: "Mostra risposta",
    hideAnswer: "Nascondi risposta",
    chooseAnswer: "Scegli la risposta corretta",
    correct: "Corretto!",
    incorrect: "Sbagliato",
    back: "Indietro",
    error: "Si è verificato un errore. Riprova.",
    tryAgain: "Riprova",
    exercise: "Esercizio",
    correctMe: "Correggi",
    correcting: "Correzione in corso...",
    score: "Punteggio",
    correctedVersion: "Versione corretta",
    corrections: "Correzioni",
    writeTranslation: "Scrivi la tua traduzione in giapponese qui sotto",
    yourTranslation: "La tua traduzione in giapponese...",
    profile: "Profilo",
    language: "Lingua",
    jlptLevel: "Livello JLPT",
    save: "Salva",
    kanjiList: "Lista Kanji",
    kanji: "kanji",
    strokes: "Tratti",
    loading: "Caricamento...",
    studySession: "Sessione di studio",
    kanjiDictionary: "Dizionario Kanji",
    searchKanji: "Cerca per kanji, lettura o significato...",
    noResults: "Nessun kanji trovato",
    loadVocabulary: "Carica esempi di vocabolario",
    apiKey: "Chiave API Anthropic",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyRequired: "Configura la tua chiave API Anthropic nelle impostazioni del profilo.",
    levelComplete: "Hai coperto tutti i kanji e la grammatica di questo livello!",
    startOver: "Ricomincia",
    nextLevel: "Livello successivo",
    kanjiProgress: "Kanji",
    grammarProgress: "Grammatica",
    reading: "Lettura",
    generateReading: "Genera testo di lettura",
    generatingReading: "Generazione in corso...",
    showFurigana: "Mostra furigana",
    hideFurigana: "Nascondi furigana",
    showTranslation: "Mostra traduzione",
    hideTranslation: "Nascondi traduzione",
    keyVocabulary: "Vocabolario chiave",
    comprehension: "Comprensione",
  },
  es: {
    appTitle: "Kurodo",
    selectLanguage: "Selecciona tu idioma",
    selectLevel: "Selecciona tu nivel JLPT",
    generate: "Generar sesión de estudio",
    generating: "Generando...",
    kanjiOfTheDay: "Kanji del día",
    grammarOfTheDay: "Gramática del día",
    writing: "Escritura",
    onyomi: "On'yomi",
    kunyomi: "Kun'yomi",
    meaning: "Significado",
    vocabulary: "Vocabulario",
    structure: "Estructura",
    examples: "Ejemplos",
    fillInBlank: "Completar la frase",
    jpToLang: "Japonés → Español",
    langToJp: "Español → Japonés",
    kanjiMeaning: "Significado del Kanji",
    revealAnswer: "Mostrar respuesta",
    hideAnswer: "Ocultar respuesta",
    chooseAnswer: "Elige la respuesta correcta",
    correct: "¡Correcto!",
    incorrect: "Incorrecto",
    back: "Volver",
    error: "Ha ocurrido un error. Por favor, inténtalo de nuevo.",
    tryAgain: "Intentar de nuevo",
    exercise: "Ejercicio",
    correctMe: "Corregir",
    correcting: "Corrigiendo...",
    score: "Puntuación",
    correctedVersion: "Versión corregida",
    corrections: "Correcciones",
    writeTranslation: "Escribe tu traducción al japonés a continuación",
    yourTranslation: "Tu traducción en japonés...",
    profile: "Perfil",
    language: "Idioma",
    jlptLevel: "Nivel JLPT",
    save: "Guardar",
    kanjiList: "Lista de Kanji",
    kanji: "kanji",
    strokes: "Trazos",
    loading: "Cargando...",
    studySession: "Sesión de estudio",
    kanjiDictionary: "Diccionario de Kanji",
    searchKanji: "Buscar por kanji, lectura o significado...",
    noResults: "No se encontraron kanji",
    loadVocabulary: "Cargar ejemplos de vocabulario",
    apiKey: "Clave API de Anthropic",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyRequired: "Por favor, configura tu clave API de Anthropic en los ajustes del perfil.",
    levelComplete: "¡Has cubierto todos los kanji y la gramática de este nivel!",
    startOver: "Empezar de nuevo",
    nextLevel: "Siguiente nivel",
    kanjiProgress: "Kanji",
    grammarProgress: "Gramática",
    reading: "Lectura",
    generateReading: "Generar texto de lectura",
    generatingReading: "Generando...",
    showFurigana: "Mostrar furigana",
    hideFurigana: "Ocultar furigana",
    showTranslation: "Mostrar traducción",
    hideTranslation: "Ocultar traducción",
    keyVocabulary: "Vocabulario clave",
    comprehension: "Comprensión",
  },
  pt: {
    appTitle: "Kurodo",
    selectLanguage: "Selecione seu idioma",
    selectLevel: "Selecione seu nível JLPT",
    generate: "Gerar sessão de estudo",
    generating: "Gerando...",
    kanjiOfTheDay: "Kanji do dia",
    grammarOfTheDay: "Gramática do dia",
    writing: "Escrita",
    onyomi: "On'yomi",
    kunyomi: "Kun'yomi",
    meaning: "Significado",
    vocabulary: "Vocabulário",
    structure: "Estrutura",
    examples: "Exemplos",
    fillInBlank: "Preencher a lacuna",
    jpToLang: "Japonês → Português",
    langToJp: "Português → Japonês",
    kanjiMeaning: "Significado do Kanji",
    revealAnswer: "Revelar resposta",
    hideAnswer: "Ocultar resposta",
    chooseAnswer: "Escolha a resposta correta",
    correct: "Correto!",
    incorrect: "Incorreto",
    back: "Voltar",
    error: "Ocorreu um erro. Por favor, tente novamente.",
    tryAgain: "Tentar novamente",
    exercise: "Exercício",
    correctMe: "Corrigir",
    correcting: "Corrigindo...",
    score: "Pontuação",
    correctedVersion: "Versão corrigida",
    corrections: "Correções",
    writeTranslation: "Escreva sua tradução em japonês abaixo",
    yourTranslation: "Sua tradução em japonês...",
    profile: "Perfil",
    language: "Idioma",
    jlptLevel: "Nível JLPT",
    save: "Salvar",
    kanjiList: "Lista de Kanji",
    kanji: "kanji",
    strokes: "Traços",
    loading: "Carregando...",
    studySession: "Sessão de estudo",
    kanjiDictionary: "Dicionário de Kanji",
    searchKanji: "Pesquisar por kanji, leitura ou significado...",
    noResults: "Nenhum kanji encontrado",
    loadVocabulary: "Carregar exemplos de vocabulário",
    apiKey: "Chave API Anthropic",
    apiKeyPlaceholder: "sk-ant-...",
    apiKeyRequired: "Por favor, configure sua chave API Anthropic nas configurações do perfil.",
    levelComplete: "Você cobriu todos os kanji e gramática deste nível!",
    startOver: "Recomeçar",
    nextLevel: "Próximo nível",
    kanjiProgress: "Kanji",
    grammarProgress: "Gramática",
    reading: "Leitura",
    generateReading: "Gerar texto de leitura",
    generatingReading: "Gerando...",
    showFurigana: "Mostrar furigana",
    hideFurigana: "Ocultar furigana",
    showTranslation: "Mostrar tradução",
    hideTranslation: "Ocultar tradução",
    keyVocabulary: "Vocabulário-chave",
    comprehension: "Compreensão",
  },
};

export const jlptLevels = [
  {
    level: "n5" as const,
    label: "N5",
    description: {
      en: "Beginner",
      fr: "Débutant",
      de: "Anfänger",
      it: "Principiante",
      es: "Principiante",
      pt: "Iniciante",
    },
  },
  {
    level: "n4" as const,
    label: "N4",
    description: {
      en: "Elementary",
      fr: "Élémentaire",
      de: "Elementar",
      it: "Elementare",
      es: "Elemental",
      pt: "Elementar",
    },
  },
  {
    level: "n3" as const,
    label: "N3",
    description: {
      en: "Intermediate",
      fr: "Intermédiaire",
      de: "Mittelstufe",
      it: "Intermedio",
      es: "Intermedio",
      pt: "Intermediário",
    },
  },
  {
    level: "n2" as const,
    label: "N2",
    description: {
      en: "Upper Intermediate",
      fr: "Intermédiaire avancé",
      de: "Obere Mittelstufe",
      it: "Intermedio avanzato",
      es: "Intermedio avanzado",
      pt: "Intermediário avançado",
    },
  },
  {
    level: "n1" as const,
    label: "N1",
    description: {
      en: "Advanced",
      fr: "Avancé",
      de: "Fortgeschritten",
      it: "Avanzato",
      es: "Avanzado",
      pt: "Avançado",
    },
  },
];
